# Generated by Django 4.2.4 on 2023-08-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_cartitem_cart_cartitem_user_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
