# Generated by Django 4.2.4 on 2023-09-12 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0008_remove_cartitem_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=100)),
                ('date_of_order', models.CharField(max_length=10)),
                ('shipping_address', models.CharField(max_length=200)),
                ('payment_method', models.CharField(max_length=10)),
                ('order_total', models.PositiveIntegerField()),
                ('ordered_item', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
