# Generated by Django 4.2.4 on 2023-09-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_order_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
    ]
